import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nutrify",
  description: "Generated by create next app",
  icons: "./nutrify.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-emerald-900 via-green-600 to-yellow-500 animate-gradient text-white`}
        >
          <Navbar />
          <div className="max-w-7xl mx-auto pt-8 p-4 min-h-screen">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
